version: '2'
services:
    friend-app:
        image: friend
        environment:
            - SPRING_PROFILES_ACTIVE=default
            - SPRING_DATA_MONGODB_URI=mongodb://friend-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=friend
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    friend-mongodb:
        extends:
            file: mongodb.yml
            service: friend-mongodb
